{{ config(
    materialized='table',
) }}
WITH final_result AS ((SELECT SAFE_CAST(metrics_value_per_conversion AS FLOAT64) AS metrics_value_per_conversion,
SAFE_CAST(segments_conversion_action AS STRING) AS segments_conversion_action,
SAFE_CAST(segments_conversion_action_category AS STRING) AS segments_conversion_action_category,
SAFE_CAST(segments_conversion_action_name AS STRING) AS segments_conversion_action_name,
SAFE_CAST(segments_conversion_attribution_event_type AS STRING) AS segments_conversion_attribution_event_type,
SAFE_CAST(segments_day_of_week AS STRING) AS segments_day_of_week,
EXTRACT(MONTH FROM date) AS segments_month,
EXTRACT(QUARTER FROM date) AS segments_quarter,
EXTRACT(WEEK FROM date) AS segments_week,
EXTRACT(YEAR FROM date) AS segments_year,
SAFE_CAST(funnel as string) as funnel,
SAFE_CAST(bidding_strategy_name AS STRING) AS bidding_strategy_name,
SAFE_CAST(campaign_advertising_channel_sub_type AS STRING) AS campaign_advertising_channel_sub_type,
SAFE_CAST(campaign_advertising_channel_type AS STRING) AS campaign_advertising_channel_type,
SAFE_CAST(campaign_bidding_strategy AS STRING) AS campaign_bidding_strategy,
SAFE_CAST(campaign_bidding_strategy_type AS STRING) AS campaign_bidding_strategy_type,
SAFE_CAST(campaign_budget_amount_micros AS INT64) AS campaign_budget_amount_micros,
SAFE_CAST(campaign_budget_explicitly_shared AS BOOL) AS campaign_budget_explicitly_shared,
SAFE_CAST(campaign_budget_has_recommended_budget AS BOOL) AS campaign_budget_has_recommended_budget,
SAFE_CAST(campaign_budget_period AS STRING) AS campaign_budget_period,
SAFE_CAST(campaign_budget_recommended_budget_amount_micros AS INT64) AS campaign_budget_recommended_budget_amount_micros,
SAFE_CAST(campaign_budget_total_amount_micros AS INT64) AS campaign_budget_total_amount_micros,
SAFE_CAST(campaign_campaign_budget AS STRING) AS campaign_campaign_budget,
SAFE_CAST(campaign_end_date AS STRING) AS campaign_end_date,
SAFE_CAST(campaign_experiment_type AS STRING) AS campaign_experiment_type,
SAFE_CAST(campaign_manual_cpc_enhanced_cpc_enabled AS BOOL) AS campaign_manual_cpc_enhanced_cpc_enabled,
SAFE_CAST(campaign_maximize_conversion_value_target_roas AS FLOAT64) AS campaign_maximize_conversion_value_target_roas,
SAFE_CAST(campaign_name AS STRING) AS campaign_name,
SAFE_CAST(campaign_percent_cpc_enhanced_cpc_enabled AS BOOL) AS campaign_percent_cpc_enhanced_cpc_enabled,
SAFE_CAST(campaign_serving_status AS STRING) AS campaign_serving_status,
SAFE_CAST(campaign_start_date AS STRING) AS campaign_start_date,
SAFE_CAST(campaign_status AS STRING) AS campaign_status,
SAFE_CAST(campaign_tracking_url_template AS STRING) AS campaign_tracking_url_template,
SAFE_CAST(campaign_url_custom_parameters AS STRING) AS campaign_url_custom_parameters,
SAFE_CAST(campaign_id AS INT64) AS campaign_id,
SAFE_CAST(customer_id AS INT64) AS customer_id,
SAFE_CAST(campaign_base_campaign AS STRING) AS campaign_base_campaign,
SAFE_CAST(metrics_conversions AS FLOAT64) AS metrics_conversions,
SAFE_CAST(metrics_conversions_value AS FLOAT64) AS metrics_conversions_value,
SAFE_CAST(metrics_interaction_event_types AS STRING) AS metrics_interaction_event_types,
SAFE_CAST(metrics_interactions AS INT64) AS metrics_interactions,
SAFE_CAST(metrics_view_through_conversions AS INT64) AS metrics_view_through_conversions,
SAFE_CAST(segments_ad_network_type AS STRING) AS segments_ad_network_type,
SAFE_CAST(segments_device AS STRING) AS segments_device,
SAFE_CAST(segments_slot AS STRING) AS segments_slot,
SAFE_CAST(_LATEST_DATE AS STRING) AS _LATEST_DATE,
SAFE_CAST(_DATA_DATE AS STRING) AS _DATA_DATE,
SAFE_CAST(media_cost AS FLOAT64) AS media_cost,
SAFE_CAST(clicks AS INT64) AS clicks,
SAFE_CAST(impressions AS FLOAT64) AS impressions,
SAFE_CAST(date AS DATE) AS date,
SAFE_CAST(campaign_name_selection AS STRING) AS campaign_name_selection,
SAFE_CAST(publisher AS STRING) AS publisher,
SAFE_CAST(media_format AS STRING) AS media_format,
SAFE_CAST(channel AS STRING) AS channel,
SAFE_CAST(creative_name AS STRING) AS creative_name,
SAFE_CAST(ad_format AS STRING) AS ad_format,
SAFE_CAST(ad_format_detail AS STRING) AS ad_format_detail,
SAFE_CAST(audience_name AS STRING) AS audience_name,
SAFE_CAST(video_completion AS FLOAT64) AS video_completion,
SAFE_CAST(video_50_completion AS FLOAT64) AS video_50_completion,
SAFE_CAST(video_25_completion AS FLOAT64) AS video_25_completion,
SAFE_CAST(video_75_completion AS FLOAT64) AS video_75_completion,
SAFE_CAST(video_views AS INT64) AS video_views,
SAFE_CAST(campaign_descr AS STRING) AS campaign_descr,
SAFE_CAST(creative_descr AS STRING) AS creative_descr FROM `polestar-main.dash_table.dash_table` ) UNION ALL (SELECT SAFE_CAST(metrics_value_per_conversion AS FLOAT64) AS metrics_value_per_conversion,
SAFE_CAST(segments_conversion_action AS STRING) AS segments_conversion_action,
SAFE_CAST(segments_conversion_action_category AS STRING) AS segments_conversion_action_category,
SAFE_CAST(segments_conversion_action_name AS STRING) AS segments_conversion_action_name,
SAFE_CAST(segments_conversion_attribution_event_type AS STRING) AS segments_conversion_attribution_event_type,
SAFE_CAST(segments_day_of_week AS STRING) AS segments_day_of_week,
EXTRACT(MONTH FROM date) AS segments_month,
EXTRACT(QUARTER FROM date) AS segments_quarter,
EXTRACT(WEEK FROM date) AS segments_week,
EXTRACT(YEAR FROM date) AS segments_year,
SAFE_CAST(funnel as string) as funnel,
SAFE_CAST(bidding_strategy_name AS STRING) AS bidding_strategy_name,
SAFE_CAST(campaign_advertising_channel_sub_type AS STRING) AS campaign_advertising_channel_sub_type,
SAFE_CAST(campaign_advertising_channel_type AS STRING) AS campaign_advertising_channel_type,
SAFE_CAST(campaign_bidding_strategy AS STRING) AS campaign_bidding_strategy,
SAFE_CAST(campaign_bidding_strategy_type AS STRING) AS campaign_bidding_strategy_type,
SAFE_CAST(campaign_budget_amount_micros AS INT64) AS campaign_budget_amount_micros,
SAFE_CAST(campaign_budget_explicitly_shared AS BOOL) AS campaign_budget_explicitly_shared,
SAFE_CAST(campaign_budget_has_recommended_budget AS BOOL) AS campaign_budget_has_recommended_budget,
SAFE_CAST(campaign_budget_period AS STRING) AS campaign_budget_period,
SAFE_CAST(campaign_budget_recommended_budget_amount_micros AS INT64) AS campaign_budget_recommended_budget_amount_micros,
SAFE_CAST(campaign_budget_total_amount_micros AS INT64) AS campaign_budget_total_amount_micros,
SAFE_CAST(campaign_campaign_budget AS STRING) AS campaign_campaign_budget,
SAFE_CAST(campaign_end_date AS STRING) AS campaign_end_date,
SAFE_CAST(campaign_experiment_type AS STRING) AS campaign_experiment_type,
SAFE_CAST(campaign_manual_cpc_enhanced_cpc_enabled AS BOOL) AS campaign_manual_cpc_enhanced_cpc_enabled,
SAFE_CAST(campaign_maximize_conversion_value_target_roas AS FLOAT64) AS campaign_maximize_conversion_value_target_roas,
SAFE_CAST(campaign_name AS STRING) AS campaign_name,
SAFE_CAST(campaign_percent_cpc_enhanced_cpc_enabled AS BOOL) AS campaign_percent_cpc_enhanced_cpc_enabled,
SAFE_CAST(campaign_serving_status AS STRING) AS campaign_serving_status,
SAFE_CAST(campaign_start_date AS STRING) AS campaign_start_date,
SAFE_CAST(campaign_status AS STRING) AS campaign_status,
SAFE_CAST(campaign_tracking_url_template AS STRING) AS campaign_tracking_url_template,
SAFE_CAST(campaign_url_custom_parameters AS STRING) AS campaign_url_custom_parameters,
SAFE_CAST(campaign_id AS INT64) AS campaign_id,
SAFE_CAST(customer_id AS INT64) AS customer_id,
SAFE_CAST(campaign_base_campaign AS STRING) AS campaign_base_campaign,
SAFE_CAST(metrics_conversions AS FLOAT64) AS metrics_conversions,
SAFE_CAST(metrics_conversions_value AS FLOAT64) AS metrics_conversions_value,
SAFE_CAST(metrics_interaction_event_types AS STRING) AS metrics_interaction_event_types,
SAFE_CAST(metrics_interactions AS INT64) AS metrics_interactions,
SAFE_CAST(metrics_view_through_conversions AS INT64) AS metrics_view_through_conversions,
SAFE_CAST(segments_ad_network_type AS STRING) AS segments_ad_network_type,
SAFE_CAST(segments_device AS STRING) AS segments_device,
SAFE_CAST(segments_slot AS STRING) AS segments_slot,
SAFE_CAST(_LATEST_DATE AS STRING) AS _LATEST_DATE,
SAFE_CAST(_DATA_DATE AS STRING) AS _DATA_DATE,
SAFE_CAST(media_cost AS FLOAT64) AS media_cost,
SAFE_CAST(clicks AS INT64) AS clicks,
SAFE_CAST(impressions AS FLOAT64) AS impressions,
SAFE_CAST(date AS DATE) AS date,
SAFE_CAST(campaign_name_selection AS STRING) AS campaign_name_selection,
SAFE_CAST(publisher AS STRING) AS publisher,
SAFE_CAST(media_format AS STRING) AS media_format,
SAFE_CAST(channel AS STRING) AS channel,
SAFE_CAST(creative_name AS STRING) AS creative_name,
SAFE_CAST(ad_format AS STRING) AS ad_format,
SAFE_CAST(ad_format_detail AS STRING) AS ad_format_detail,
SAFE_CAST(audience_name AS STRING) AS audience_name,
SAFE_CAST(video_completion AS FLOAT64) AS video_completion,
SAFE_CAST(video_50_completion AS FLOAT64) AS video_50_completion,
SAFE_CAST(video_25_completion AS FLOAT64) AS video_25_completion,
SAFE_CAST(video_75_completion AS FLOAT64) AS video_75_completion,
SAFE_CAST(video_views AS INT64) AS video_views,
SAFE_CAST(campaign_descr AS STRING) AS campaign_descr,
SAFE_CAST(creative_descr AS STRING) AS creative_descr FROM `polestar-main.dash_table_search.dash_table_search` ) )
SELECT
  -- Replace publisher from table2 if matched, else keep original
  COALESCE(t2.present, t1.publisher) AS publisher,
  t1.*
EXCEPT(publisher) -- exclude original publisher to avoid duplicate columns

FROM final_result AS t1
LEFT JOIN `together-internal.publisher_naming.publisher_naming` AS t2
  ON LOWER(t1.publisher) = LOWER(t2.publisher)
