name: Automated Docker Image CI

on:
  # Job Trigger: Pull Request
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - ".github/**"
      - "terraform/**"
      #- "**/orchestrate/**"

jobs:



  # 2. Second job: Detect which folders changed, get changed folders for project
  setup_project:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      project: ${{ steps.filter.outputs.project }}
      dag: ${{ steps.filter.outputs.dag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Filter changed folders
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dag:
              - "**/orchestrate/**"
            project:
              - "**"
              - "!README.md"
              - "!.github/**"
              - "!terraform/**"
              - "!**/orchestrate/**"
      # record the folder change if the change are not dag file 
      - name: Get changed folders
        id: set-matrix
        if: steps.filter.outputs.project == 'true' 
        run: |
          # Get unique top-level directory names
          FOLDERS=$(git diff --name-only HEAD^ HEAD |grep -v '/orchestrate/'|grep -v 'README.md'|grep -v '.github/'|grep -v '/ci_test.sh'|grep -v '/client_name.py' | grep -v '/docker_build.py'| cut -d/ -f1 | sort -u | jq -R . | jq -s -c .)
          echo "matrix=$FOLDERS" >> $GITHUB_OUTPUT
  
  # 3. Third job: Detect which folders changed, get change folder for orchestrate DAG
  setup_dag:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-dag-matrix.outputs.matrix }}
      project: ${{ steps.filter.outputs.project }}
      dag: ${{ steps.filter.outputs.dag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Filter changed folders
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dag:
              - "**/orchestrate/**"
            project:
              - "**"
              - "!README.md"
              - "!.github/**"
              - "!terraform/**"
              - "!**/orchestrate/**"
      # record the folder change if the change are not dag file 
      - name: Get changed folders
        id: set-dag-matrix
        if: steps.filter.outputs.dag == 'true'
        run: |
          # Get unique top-level directory names
          FOLDERS=$(git diff --name-only HEAD^ HEAD |grep '/orchestrate/'| cut -d/ -f1 | sort -u | jq -R . | jq -s -c .)
          echo "matrix=$FOLDERS" >> $GITHUB_OUTPUT
  # 4. Fourth job: Upload the DAG to the Composer environment
  upload_dag:
    permissions:
      id-token: write
      contents: read
    needs:
      - setup_dag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.setup_dag.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud with Service Account
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/364275589560/locations/global/workloadIdentityPools/amp-pool-unique/providers/github-resource-pool"
          service_account: "impact-ci-ci-cd-service-accoun@together-internal.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload the DAG
        run: |
          gcloud composer environments storage dags import \
            --project=together-internal \
            --location=australia-southeast1 \
            --environment=meltano \
            --source=${{ matrix.folder }}/orchestrate/dags/airflow/${{ matrix.folder }}.py


  # 5. Fifth job: Build the Docker image for the project
  build:
    permissions:
      id-token: write
      contents: read
    needs: 
      - setup_project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.setup_project.outputs.matrix) }}
    steps:
      - name: Build the Docker image for the ${{ matrix.folder }} folder


        run: echo "Currently building in ${{ matrix.folder }}" 
 

      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud with Service Account
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/364275589560/locations/global/workloadIdentityPools/amp-pool-unique/providers/github-resource-pool"
          service_account: "impact-ci-ci-cd-service-accoun@together-internal.iam.gserviceaccount.com"

      - name: Invoke gcloud setup
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev --quiet

      - name: Invoke SSH agent with ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_SECRET }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build the Docker image
        working-directory: ${{ matrix.folder }}
        run: python ../centralize_data/docker_build.py ${{ matrix.folder }} --build-only

      - name: Test the Docker image
        working-directory: ${{ matrix.folder }}
        run: python ../centralize_data/docker_build.py ${{ matrix.folder }} --test-only

      - name: Push the Docker image
        working-directory: ${{ matrix.folder }}
        run: |
          python ../centralize_data/docker_build.py ${{ matrix.folder }} --push-only
